Feature/idea codeformatter delete
i-Cell-Mobilsoft-Open-Source/java-dev-tools pull request #16
Opened 2023-04-27 13:10 UTC by speter555

2023-04-27 13:15 UTC, speter555 commented
#9 closed
#8 closed

2023-04-27 13:37 UTC, petrenyi-mark requested changes

2023-04-27 13:37 UTC, petrenyi-mark commented on codeformatter/eclipse/icellmobilsoft-eclipse-code-formatter.xml
> +        <setting id="org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation" value="16"/>
ezek voltak a régi értékek, 0.1.0-n,
az új formatter már main-en ott van

2023-05-09 10:28 UTC, speter555 commented on codeformatter/eclipse/icellmobilsoft-eclipse-code-formatter.xml
> +        <setting id="org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation" value="16"/>
javítva

2023-05-09 10:30 UTC, czenczl approved these changes

2023-05-09 12:39 UTC, rombow approved these changes

2023-05-09 20:20 UTC, bucherarnold approved these changes

2023-05-09 20:20 UTC, bucherarnold approved these changes

2023-06-09 08:56 UTC, vasizs approved these changes

2023-06-14 12:58 UTC, petrenyi-mark approved these changes

2023-06-14 13:07 UTC, merged